# config/yaml/task.dcm.yml
task2:
  type: entity
  table: tasks
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
    description:
      type: string
    created_at:
      type: timestamp
    update_at:
      type: timestamps